export const LANGUAGE_OPTIONS = [
  'Portuguese',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Japanese',
  'Korean',
  'Mandarin Chinese',
  'Arabic',
  'Hindi',
  'Russian',
  'Turkish',
  'Dutch',
  'Swedish',
  'Polish',
  'Greek',
  'Hebrew',
  'Vietnamese',
  'Thai',
  'Indonesian',
] as const;

export const INTEREST_OPTIONS = [
  'technology',
  'sports',
  'music',
  'movies',
  'history',
  'science',
  'business',
  'health',
  'travel',
  'food',
  'gaming',
  'art',
  'politics',
  'nature',
  'education',
] as const;

export const REDDIT_TOPIC_SOURCE_MAP: Record<string, string> = {
  technology: 'technology',
  sports: 'sports',
  music: 'music',
  movies: 'movies',
  history: 'history',
  science: 'science',
  business: 'business',
  health: 'health',
  travel: 'travel',
  food: 'food',
  gaming: 'gaming',
  art: 'art',
  politics: 'politics',
  nature: 'nature',
  education: 'education',
};
